version: '3.9'

services:
  app:
    build: .
    container_name: adfinem-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    networks:
      - adfinem-network

  nginx:
    image: nginx:alpine
    container_name: adfinem-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - adfinem-network

  mysql:
    image: mysql:8.3
    container_name: adfinem-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: adfinem
      MYSQL_USER: adfinemuser
      MYSQL_PASSWORD: adfinempass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - adfinem-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adfinem-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: adfinemuser
      PMA_PASSWORD: adfinempass
    networks:
      - adfinem-network
    depends_on:
      - mysql

networks:
  adfinem-network:
